In [2]:
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pickle

In [4]:
df = pd.read_csv('penyakit_ginjal_kronik.csv')
df.head()

,umur,tekanandarah,albumin,gds,ureum,kreatinin,hemoglobin,MCV,seldarahputih,seldarahmerah,hipertensi,diabetes,nafsumakan,anemia,klasifikasi
0,48.0,80.0,1.0,121.0,36.0,1.2,15.4,44,7800,5.2,yes,yes,good,no,ckd
1,7.0,50.0,4.0,NaN,18.0,0.8,11.3,38,6000,4.5,no,no,good,no,ckd
2,62.0,80.0,2.0,423.0,53.0,1.8,9.6,31,7500,4.3,no,yes,poor,yes,ckd
3,48.0,70.0,4.0,117.0,56.0,3.8,11.2,32,6700,3.9,yes,no,poor,yes,ckd
4,51.0,80.0,2.0,106.0,26.0,1.4,11.6,35,7300,4.6,no,no,good,no,ckd

In [5]:
df = df.dropna()
df = df.reset_index(drop=True)
df.replace({'yes': 1, 'no': 0}, inplace=True)
df.replace({'ckd': 1, 'notckd': 0}, inplace=True)
df.replace({'good': 1, 'poor': 0}, inplace=True)
df.head()

,umur,tekanandarah,albumin,gds,ureum,kreatinin,hemoglobin,MCV,seldarahputih,seldarahmerah,hipertensi,diabetes,nafsumakan,anemia,klasifikasi
0,48.0,80.0,1.0,121.0,36.0,1.2,15.4,44,7800,5.2,1,1,1,0,1
1,62.0,80.0,2.0,423.0,53.0,1.8,9.6,31,7500,4.3,0,1,0,1,1
2,48.0,70.0,4.0,117.0,56.0,3.8,11.2,32,6700,3.9,1,0,0,1,1
3,51.0,80.0,2.0,106.0,26.0,1.4,11.6,35,7300,4.6,0,0,1,0,1
4,60.0,90.0,3.0,74.0,25.0,1.1,12.2,39,7800,4.4,1,1,1,0,1

In [8]:
# Pisahkan fitur dan target
X = df[['umur', 'tekanandarah', 'albumin', 'gds', 'ureum', 'kreatinin', 'hemoglobin', 'MCV', 'seldarahputih', 'seldarahmerah', 'hipertensi', 'diabetes', 'nafsumakan', 'anemia']]
y = df['klasifikasi']

# Bagi dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Latih model SVM
model = svm.SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
pickle.dump(model, open('model.pkl','wb'))